### ISSUE TITLE
Webpack & Vue 坑

### ISSUE THREAD

**Issue by 007sair** [007sair/007sair.github.io#4]
# Webpack & Vue 坑

@(webpack)

## 1.webpack-dev-server不起作用

`webpack-dev-server`无法实时刷新？

1. 修改`webpack.config.js`配置的`scripts`项
```
"scripts": {
    "start": "webpack-dev-server --hot --inline"
}
```

2. 在`webpack.config.js`的`output`项内添加进行修改：
```
//指向异步加载的路径
publicPath: __dirname + '/build/'
```
替换为：
```
publicPath: '/build/'
```

3. 运行`npm start`

为什么这样做呢？因为我们这前用`webpack`是把组件异步加载在本地上，而我们用了热替换后是地址委托到了`http://localhost:8080/`端口了，所以要去掉`__dirname`(指向本地根目录)，一切准备完毕了，接下来直接运行`npm start`，然后打开`http://localhost:8080/`就可以访问并实时刷新。

## 2.sass&css单文件打包

很多时候我们不喜欢`require`进来的css或者sass被添加到html的`style`标签中，而是作为单独的css文件被html引用。

1. 安装`extract-text-webpack-plugin`插件
```
npm install extract-text-webpack-plugin --save-dev
```

2. 配置`webpack.config.js`
```
//a.先require进来
var ExtractTextPlugin = require("extract-text-webpack-plugin");
//b.再添加到plugins中
plugins: [
	new ExtractTextPlugin("styles.css")
]
```

3. 修改`module`的`loaders`配置
```
//需要知道的是，ExtractTextPlugin.extract 第二个参数(或拆分为多个参数)中 loader 的执行顺序是从右到左，即先对引入的 .sass 使用 sass loader 得到编译后的 css 再使用 css-loader 按照正常 css-loader 的方式处理。
loaders: [
	{
		test: /\.css$/,
		loader: ExtractTextPlugin.extract("style-loader", "css-loader")
	}, {
		test: /\.scss$/,
		loader: ExtractTextPlugin.extract("style-loader", "css-loader!sass-loader")
	}
]
```

参考：[http://webpack.github.io/docs/stylesheets.html#separate-css-bundle](http://webpack.github.io/docs/stylesheets.html#separate-css-bundle)

## 3.Vue踩坑之一：template无法在table中使用

未解决。

## 4.Vue踩坑之二：字体在生产环境的bug

正常开发时我们会这么设置字体：

```css
.wrap{
  font-family: "微软雅黑"; /* 或者 */
  font-family: "\5FAE\8F6F\96C5\9ED1";
}
```

执行 `npm run build`后，字体没生效，F12查看发现代码变成这样了：

```css
.wrap{
  font-family: \\5FAE\8F6F\96C5\9ED1;
}
```

修改方法：

```css
.wrap{
  font-family: \5FAE\8F6F\96C5\9ED1; /* 去掉双引号！ */
}
```
